import modal
import subprocess
import os

blender_image = (
    modal.Image.debian_slim()
    .apt_install(
        "wget", "xz-utils", "xvfb", "ffmpeg", 
        "libxrender1", "libxi6", "libxkbcommon0", "libgl1-mesa-glx", 
        "libsm6", "libice6", "libxext6", "libx11-6",
        "libegl1", "libopengl0", "libx11-xcb1" 
    )
    .run_commands(
        "wget https://download.blender.org/release/Blender4.1/blender-4.1.0-linux-x64.tar.xz",
        "tar -xf blender-4.1.0-linux-x64.tar.xz",
        "mv blender-4.1.0-linux-x64 /usr/local/blender"
    )
    .add_local_dir(".", remote_path="/project") 
)

app = modal.App("compoxel-render-farm")

shared_volume = modal.Volume.from_name("compoxel-storage", create_if_missing=True)

@app.function(image=blender_image, volumes={"/vol": shared_volume})
def prep_volume():
    import shutil
    if os.path.exists("/vol/frames"):
        shutil.rmtree("/vol/frames")
    os.makedirs("/vol/frames", exist_ok=True)
    shared_volume.commit()
    print("[CLOUD] Shared volume cleaned and ready for new frames!")

@app.function(
    image=blender_image, 
    gpu="T4", 
    timeout=1800,           
    concurrency_limit=10,   
    volumes={"/vol": shared_volume} 
)
def render_frame_batch(start_frame: int, end_frame: int, abc_filename: str):
    import glob
    
    shared_volume.reload()
    
    blend_files = glob.glob("/project/*.blend")
    if not blend_files:
        raise FileNotFoundError("Could not find any .blend file in the directory!")
    target_blend = blend_files[0]
    
    # FIX: Dynamically inject the target .abc file into the Blender cache modifier
    blender_script = f"""import bpy
bpy.context.scene.render.image_settings.file_format = 'PNG'
bpy.context.scene.render.filepath = '/vol/frames/frame_'
for obj in bpy.data.objects:
    for mod in obj.modifiers:
        if mod.type == 'MESH_SEQUENCE_CACHE' and mod.cache_file:
            mod.cache_file.filepath = '/vol/{abc_filename}'
"""
    with open("/tmp/fix_paths.py", "w") as f:
        f.write(blender_script)
        
    cmd = f"xvfb-run -a /usr/local/blender/blender -b {target_blend} -P /tmp/fix_paths.py -s {start_frame} -e {end_frame} -a"
    subprocess.run(cmd, shell=True, check=True, capture_output=True, text=True)
    
    shared_volume.commit() 
    print(f"[CLOUD] Rendered batch {start_frame} to {end_frame} successfully.")

@app.function(image=blender_image, timeout=1200, volumes={"/vol": shared_volume})
def stitch_video(algo: str) -> bytes:
    print(f"[CLOUD] All frames generated! Stitching into final {algo} MP4...")
    
    shared_volume.reload() 
            
    video_path = f"/tmp/compoxel_{algo}_render.mp4"
    ffmpeg_cmd = f"ffmpeg -y -framerate 30 -i '/vol/frames/frame_%04d.png' -c:v libx264 -pix_fmt yuv420p {video_path}"
    subprocess.run(ffmpeg_cmd, shell=True, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    with open(video_path, "rb") as f:
        return f.read()

# NEW: The entrypoint now accepts an argument from your terminal!
@app.local_entrypoint()
def main(algo: str = "hybrid"):
    algo = algo.lower()
    valid_algos = ["tree", "mesh", "hybrid"]
    
    if algo not in valid_algos:
        print(f"❌ Error: Invalid algorithm '{algo}'. Must be one of: {valid_algos}")
        return

    abc_filename = f"compoxel_{algo}.abc"
    TOTAL_FRAMES = 60 # Matched to the 60 frames generated by visuals script
    NUM_BATCHES = 10  # 6 frames per batch
    
    print(f"[LOCAL] Formatting cloud volume for the {algo.upper()} render...")
    prep_volume.remote()
    
    frames_per_batch = max(1, TOTAL_FRAMES // NUM_BATCHES)
    batches = []
    for i in range(0, TOTAL_FRAMES, frames_per_batch):
        start = i
        end = min(i + frames_per_batch - 1, TOTAL_FRAMES - 1)
        batches.append((start, end, abc_filename)) # Pass the filename to the cloud workers!
    
    print(f"[LOCAL] Dispatching {TOTAL_FRAMES} frames of {abc_filename} across {len(batches)} batches...")
    
    list(render_frame_batch.starmap(batches))
    
    print(f"[LOCAL] Swarm finished! Sending to the stitching node...")
    video_bytes = stitch_video.remote(algo)
    
    output_filename = f"compoxel_{algo}_render.mp4"
    with open(output_filename, "wb") as f:
        f.write(video_bytes)
        
    print(f"✅ Render complete! Saved '{output_filename}' to your local folder.")